config/routes.rb
Rails.application.routes.draw do
  # # new
  # get 'questions/new'

  # #create
  # post 'questions', to: 'questions#create', as: :create_question

  # # index
  # get 'questions', to: 'questions#index'

  # # show
  # get 'questions/:id', to: 'questions#show', as: :question

  # #edit
  # get 'questions/:id/edit', to: 'questions#edit', as: :edit_question

  # #update
  # patch 'questions/:id', to: 'questions#update'

  # # destroy
  # delete 'questions/:id', to: 'questions#destroy', as: :delete_question

  resources :questions



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root"welcome#index" #setup the root path
  get('/welcome',{to: 'welcome#index'}) 
  get('/goodbye',{to: 'welcome#goodbye', as: :goodbye}) #as options give you ability to change the name
  get('/form_example',{to: 'welcome#form_example'}) 
  # get('/questions/:id') #dynamic id will replace :id with the number or params in url
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Goodbye", goodbye_path %>
      <%= link_to "Welcome", root_path %>
      <%= link_to "Form Example", form_example_path %>
      <%= link_to "Questions", questions_path %>
      <%= link_to "New Question", new_question_path %>
    </nav>
    <%= flash[:notice] || flash[:alert] %>
    <%= yield %>
  </body>
</html>